version: 2.1
jobs:
  toxify:
      parameters:
        tox-env:
          type: string
      docker:
        - image: circleci/python:3.7-node
      steps:
        - checkout
        - run: git submodule sync
        - run: git submodule update --init
        - run: pip install tox && tox -e << parameters.tox-env >>
workflows:
  version: 2
  planemo:
    jobs:
    - toxify:
        matrix:
          parameters:
            tox-env:
              - "py37-diagnostic-unit-servebasic-gx-dev"
              - "py37-unit-nonredundant-noclientbuild-noshed-gx-2005"
              - "py37-unit-nonredundant-noclientbuild-noshed-gx-dev"
              - "py37-unit-nonredundant-noclientbuild-noshed"
