version: 2.1
jobs:
  toxify:
      parameters:
        tox-env:
          type: string
      docker:
        - image: python:3.5
      steps:
        - checkout
        - run:
            name: "Pull Submodules"
            command: |
              git submodule init
              git submodule update --remote
        - run: pip install tox && tox -e << parameters.tox-env >>
workflows:
  version: 2
  myproj:
    jobs:
    - toxify:
        matrix:
          parameters:
            tox-env: ["py35-diagnostic-unit-servebasic-gx-dev"]
