version: 2.1
jobs:
  toxify:
      parameters:
        tox-env:
          type: string
      docker:
        - image: python:3.5
      steps:
        - checkout
        - run: git submodule sync
        - run: git submodule update --init
workflows:
  version: 2
  myproj:
    jobs:
    - toxify:
        matrix:
          parameters:
            tox-env: ["py35-diagnostic-unit-servebasic-gx-dev"]
